### ISSUE TITLE
Management Module - Player Info

### ISSUE THREAD

**Issue by MiaYWei** [MiaYWei/Group_G_UNO-Card-Game#13]
* store_player_details()

**Comment by krithigasr** [comment]
Adding get_player_name() From release 1 here to support score board display

**Comment by MiaYWei** [comment]
![image](https://user-images.githubusercontent.com/33041048/101819628-85221780-3af3-11eb-8b59-53ab98ad1e0d.png)
Player name feature already implemented in Release 1.
